from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('affiliate/', views.affiliate, name="affiliate"),
    path('contact/', views.contact, name="contact"),
    path('covid/', views.covid, name="covid"),
    path('day-labor/', views.day_labor, name="day-labor"),
    path('claims/', views.claims, name="claims"),
    path('faq/', views.faq, name="faq"),
    path('ca_privacy/', views.ca_privacy, name="ca_privacy"),
    path('guarantee/', views.guarantee, name="guarantee"),
    path('license/', views.license, name="license"),
    path('privacy/', views.privacy, name="privacy"),
    path('legal/', views.legal, name="legal"),
    path('login/', views.login, name="login"),
    path('furniture/', views.furniture, name="furniture"),
    path('loading/', views.loading, name="loading"),
    path('packing/', views.packing, name="packing"),
    path('unloading/', views.unloading, name="unloading"),
    path('move-help/', views.move_help, name="move-help"),
    path('movers-academy/', views.movers_academy, name="movers-academy"),
    path('moving/', views.moving, name="moving"),
    path('corporate-relocation/', views.corporate_relocation, name="corporate-relocation"),
    path('military-move/', views.military_move, name="military-move"),
    path('moving-containers/', views.moving_containers, name="moving-containers"),
    path('office-movers/', views.office_movers, name="office-movers"),
    path('rental-truck/', views.rental_truck, name="rental-truck"),
    path('semi-freight-trailer/', views.semi_freight_trailer, name="semi-freight-trailer"),
    path('moving-companies/', views.moving_companies, name="moving-companies"),
    path('long-distance/', views.long_distance, name="long-distance"),
    path('moving-cost/', views.moving_cost, name="moving-cost"),
    path('my-move/', views.my_move, name="my-move"),
    path('how-it-works/', views.how_it_works, name="how-it-works"),
    path('moving-day/', views.moving_cost, name="moving-day"),
    path('sign-up/', views.sign_up, name="sign-up"),
    path('sitemap/', views.sitemap, name="sitemap"),
]